name: todo_mobx
description: A project for studing mobX

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6+1
  json_annotation: ^4.5.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  auto_route: ^4.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  overlay_support: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0
  mobx_codegen: ^2.0.7
  auto_route_generator: ^4.0.0

flutter:

  uses-material-design: true

 